Hcap 329 pagination bug (WIP)
bcgov/hcap pull request #239
Opened 2021-01-22 02:00 UTC by mauriciofreshw

2021-01-22 20:32 UTC, ashtonmeuser approved these changes

2021-01-22 20:35 UTC, fwkendall approved these changes

2021-01-22 20:56 UTC, ashtonmeuser requested changes

2021-01-22 20:56 UTC, ashtonmeuser commented on server/services/participants-helper.js
> +          status: ['open', 'prospecting', 'interviewing', 'offer_made', 'rejected'],
This causes the Hired tab to be empty for employers,

2021-01-26 19:50 UTC, Zenen-freshworks approved these changes
Nice! I'll have to investigate more into what a 'view' is in the context of databases but it looks good to me.

2021-01-26 20:19 UTC, mauriciofreshw commented
> Nice! I'll have to investigate more into what a 'view' is in the context of databases but it looks good to me.

Basically a query masked as a table.

2021-01-28 19:36 UTC, ashtonmeuser approved these changes

2021-01-28 19:39 UTC, Zenen-freshworks approved these changes

2021-01-28 19:52 UTC, merged