Update role/sites feature
bcgov/hcap pull request #261
Opened 2021-02-03 01:08 UTC by mauriciofreshw

2021-02-03 17:42 UTC, Zenen-freshworks requested changes
I'm getting an undefined error on filtering by None in ParticipantsView.

2021-02-03 17:42 UTC, Zenen-freshworks commented on client/src/constants/label.js
> +};
factoring stuff out of participantsview, nice!

2021-02-03 17:42 UTC, Zenen-freshworks commented on cypress/integration/participantView.spec.js
> +    cy.get('ul.MuiMenu-list[role=listbox] > li').should('have.length', 7);
Question: if we have None as an option, should "Preferred Location" still be available as a catch-all? Do they serve different purposes?

2021-02-03 18:31 UTC, Zenen-freshworks approved these changes

2021-02-03 18:37 UTC, Zenen-freshworks submitted a review, later dismissed

2021-02-03 18:59 UTC, Zenen-freshworks approved these changes

2021-02-04 00:03 UTC, fwkendall commented on client/src/pages/private/EOIView.js
> +        ? Object.values(regionLabelsMap).filter(value => value !== 'None')
I think this is incorrect, if I'm reading it right - MoH and superuser should have access to None for EEOIs

2021-02-04 00:04 UTC, fwkendall commented on client/src/pages/private/EOIView.js
> +        ? Object.values(regionLabelsMap).filter(value => value !== 'None')
Note: does not apply to participants, None is only needed for EEOIs

2021-02-04 00:07 UTC, fwkendall commented on server/server.js
> +app.post(`${apiBaseUrl}/update-user`,
should be patch :)

2021-02-04 00:09 UTC, fwkendall commented on server/server.js
> +      action: 'update-user_post',
just commenting so we remember to update this according to the endpoint update (user_patch)

2021-02-04 00:10 UTC, fwkendall commented on server/server.js
> +      granted_access_to: req.body.userId,
this key should probably have a different name for this type of action - user_id would be fine IMO (honestly I think it should have been like this for the other endpoint too, but that ship has sailed)

2021-02-04 00:11 UTC, fwkendall commented on server/server.js
> +      granted_access_to: req.body.userId,
I guess we might want to leave it as-is, even though I think it's a bad key, so that it's consistent

2021-02-04 00:48 UTC, ashtonmeuser approved these changes

2021-02-04 00:48 UTC, Zenen-freshworks approved these changes

2021-02-04 00:49 UTC, merged