HCAP-421 Add link to BC homepage
bcgov/hcap pull request #346
Opened 2021-04-26 21:46 UTC by arranfw

Modify logo alt for better clarity

https://freshworks.atlassian.net/browse/HCAP-421

- [ ]  Tested on dev

2021-04-26 23:08 UTC, Zenen-freshworks approved these changes
Seems like a straightforward PR!

2021-04-27 16:28 UTC, ashtonmeuser requested changes

2021-04-27 16:28 UTC, ashtonmeuser commented on client/src/components/generic/Header.js
> +                  alt="Government of british columbia home"
Nitpick: casing.
```suggestion
                  alt="Government of British Columbia"
```

2021-04-27 16:28 UTC, ashtonmeuser commented on client/src/components/generic/Header.js
> +                  alt="Government of british columbia home"
```suggestion
                  alt="Government of British Columbia"
```

2021-04-27 17:09 UTC, ashtonmeuser submitted a review, later dismissed

2021-04-27 17:27 UTC, ashtonmeuser approved these changes

2021-04-27 23:53 UTC, Zenen-freshworks commented on client/src/components/generic/Header.js
>      flexShrink: 0, // Logo should hold its own
this logo ain't no pushover

2021-04-27 23:53 UTC, Zenen-freshworks approved these changes

2021-04-27 23:53 UTC, merged