Hcap 662 new email text
bcgov/hcap pull request #409
Opened 2021-06-04 21:31 UTC by dbayly-freshworks

- Rand NPM audit fix
- Updated copy of email 

<img width="678" alt="Screen Shot 2021-06-04 at 2 19 27 PM" src="https://user-images.githubusercontent.com/54554766/120864758-92b7d780-c541-11eb-9843-4715f7ce4bd7.png">

2021-06-04 22:05 UTC, fwpushan submitted a review, later dismissed

2021-06-04 22:07 UTC, arranfw requested changes
👁️

2021-06-04 22:07 UTC, arranfw commented on server/scripts/sendEmailBlast.js
> +        <p>If you no longer wish to participate or be considered for employment opportunities, please email us with the subject line WITHDRAW to <b>HCAPInfoQuery@gov.bc.ca</b> or or click the link be
```suggestion
        <p>If you no longer wish to participate or be considered for employment opportunities, please email us with the subject line WITHDRAW to <b>HCAPInfoQuery@gov.bc.ca</b> or click the link below.</p>
```

2021-06-04 22:08 UTC, arranfw commented on server/scripts/sendEmailBlast.js
> +        <p>If you no longer wish to participate or be considered for employment opportunities, please email us with the subject line WITHDRAW to <b>HCAPInfoQuery@gov.bc.ca</b> or or click the link be
How long has this been in here and how many times have we overlooked it

2021-06-07 14:10 UTC, arranfw approved these changes

2021-06-07 15:58 UTC, fwpushan approved these changes

2021-06-07 17:00 UTC, fwkendall approved these changes

2021-06-07 17:02 UTC, merged