HCAP-699 withdrawal tab is available on site details view
bcgov/hcap pull request #447
Opened 2021-07-12 20:52 UTC by Zenen-freshworks

When a participant has been withdrawn from the program after being hired, they will be viewable under the "Withdrawn Participants" tab on the Site Details view.

2021-07-12 21:31 UTC, fwpushan requested changes
I will suggest you 
1. Use same Context, state and reducer for tab selection like Participant table
2. You can use url parameter to save selected tab state (to persist user selection between page refresh)
We can discuss on this.

2021-07-14 21:47 UTC, Zenen-freshworks commented
<img width="1440" alt="Screen Shot 2021-07-14 at 2 42 00 PM" src="https://user-images.githubusercontent.com/75634256/125697203-06d7b8d0-c2e4-4140-a8d4-ee7895717a5c.png">
<img width="1440" alt="Screen Shot 2021-07-14 at 2 42 12 PM" src="https://user-images.githubusercontent.com/75634256/125697190-3bf151b3-f983-4566-8b25-d02ecd47b1ef.png">

SiteParticipantsTable has been refactored with a TabContext to hold data. Site Details have been added as a tab rather than basic display info.

2021-07-15 15:15 UTC, fwpushan reviewed
Great job. All looks good, I have some naming suggestion. Please check comments.

2021-07-15 15:15 UTC, fwpushan commented on client/src/providers/TabContext.js
> +const TabContext = React.createContext();
TabContext is very generic, I will suggest a specific name like SiteDetailViewTabContext / SiteDetailTabContext

2021-07-15 15:15 UTC, fwpushan commented on client/src/providers/TabContext.js
> +const TabProvider = ({ selectedTab, siteId, children }) => {
Also same naming suggestion as TabContext

2021-07-15 15:15 UTC, fwpushan commented on client/src/providers/index.js
> +export * as TabContext from './TabContext';
Same naming suggestion

2021-07-15 22:04 UTC, fwpushan submitted a review, later dismissed
Nice job

2021-07-16 16:41 UTC, dbayly-freshworks approved these changes

2021-07-16 16:42 UTC, dbayly-freshworks approved these changes

2021-07-16 16:43 UTC, fwpushan approved these changes

2021-07-16 17:04 UTC, merged