[HCAP-843] Add console logger as fallback for OCP bug
bcgov/hcap pull request #518
Opened 2021-08-17 19:07 UTC by vyasworks

2021-08-17 19:52 UTC, Zenen-freshworks submitted a review, later dismissed

2021-08-17 19:56 UTC, fwpushan requested changes
I switched to universal json logger for all env. Please check latest code.

2021-08-18 17:23 UTC, vyasworks commented
We will need the formatted logger until we have the OCP bug resolved, if we dont, then we will not see any logs in Kibana.

2021-08-18 18:58 UTC, vyasworks commented
Local logs look like this now. 
![image](https://user-images.githubusercontent.com/67800715/129956253-3a3b01b3-cda1-40fe-bfac-6054cb236d0c.png)

2021-08-18 22:21 UTC, fwpushan approved these changes

2021-08-18 22:27 UTC, Zenen-freshworks approved these changes

2021-08-18 23:17 UTC, merged