HCAP-1164: Select Site modal
bcgov/hcap pull request #683
Opened 2022-04-18 19:56 UTC by alva-fresh

https://freshworks.atlassian.net/browse/HCAP-1164
Added a new modal for Participant Table. This modal appears when somebody is trying to Engage a participant

This is a subtask for HCAP-1107

https://www.figma.com/proto/35c5C0DyTEOxJ4N4DIaADL/HCAP-Design?node-id=2002%3A19657&viewport=241%2C48%2C0.36&scaling=min-zoom&starting-point-node-id=2002%3A19657

_Note_: this is for single participant only

2022-04-18 20:10 UTC, fwpushan requested changes
Good job. Please check my comments. I also added some tech-notes in ticket (sub-task)

2022-04-18 20:10 UTC, fwpushan commented on client/src/components/modal-forms/SelectProspectingSiteForm.js
> +              { value: 'opt1', label: 'option 1' },
get value from auth-context.

2022-04-18 20:10 UTC, fwpushan commented on client/src/constants/validation.js
> +export const SitesSchema = yup.object().shape({
You need to rebase with master .... validation.js is refactored.

2022-04-18 20:13 UTC, fwpushan commented on client/src/components/modal-forms/SelectProspectingSiteForm.js
> +            name='participantSites'
`prospectingSites` is more appropriate here.

2022-04-18 20:14 UTC, fwpushan commented on client/src/components/modal-forms/SelectProspectingSiteForm.js
> +            name='participantSites'
```suggestion
            name='prospectingSites'
```

2022-04-19 21:08 UTC, alva-fresh commented on client/src/components/modal-forms/SelectProspectingSiteForm.js
> +            name='participantSites'
Good point!

2022-04-20 14:31 UTC, fwpushan requested changes
All good just one change recommendation.

2022-04-20 17:26 UTC, fwpushan approved these changes

2022-04-20 17:53 UTC, merged