HCAP-1219 | Validation Errors on Form after changing type field
bcgov/hcap pull request #731
Opened 2022-05-26 19:35 UTC by taraepp

Ticket: https://freshworks.atlassian.net/browse/HCAP-1219
This one too: https://freshworks.atlassian.net/browse/HCAP-1220

Forced the form to not consider the other fields on the form touched after changing type in select box.

2022-05-26 19:50 UTC, fwpushan requested changes
Suggested some small changes.

2022-05-26 19:50 UTC, fwpushan commented on client/src/components/modal-forms/ArchiveHiredParticipantForm.js
> +      // validateOnBlur={true}
Remove this dead codes

2022-05-26 22:00 UTC, alva-fresh approved these changes

2022-05-27 14:12 UTC, fwpushan approved these changes

2022-05-27 15:52 UTC, merged